# Generated by Django 5.1.3 on 2025-01-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptask',
            name='deadline',
            field=models.DateField(blank=True),
        ),
    ]
