# Generated by Django 5.1.3 on 2025-01-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_apptask_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptask',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
